"""estrutura_inicial_mvp

Revision ID: dcbca6699d38
Revises: 
Create Date: 2026-07-11 10:56:00.968969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcbca6699d38'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_fidelizacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('tipo_recompensa', sa.String(), nullable=True),
    sa.Column('taxa_conversao', sa.Float(), nullable=True),
    sa.Column('valor_ponto_em_dinheiro', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_fidelizacao_id'), 'config_fidelizacao', ['id'], unique=False)
    op.create_table('configuracoes_ia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('permitir_descontos', sa.Boolean(), nullable=True),
    sa.Column('desconto_maximo', sa.Float(), nullable=True),
    sa.Column('permitir_upsell', sa.Boolean(), nullable=True),
    sa.Column('tom_de_voz', sa.String(), nullable=True),
    sa.Column('teto_interacoes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracoes_ia_id'), 'configuracoes_ia', ['id'], unique=False)
    op.create_table('grupo_modificadores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('min_selecoes', sa.Integer(), nullable=True),
    sa.Column('max_selecoes', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupo_modificadores_id'), 'grupo_modificadores', ['id'], unique=False)
    op.create_table('mensagens_whatsapp',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cliente_telefone', sa.String(), nullable=False),
    sa.Column('remetente', sa.String(), nullable=False),
    sa.Column('conteudo', sa.String(), nullable=False),
    sa.Column('transcricao', sa.String(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_whatsapp_id'), 'mensagens_whatsapp', ['id'], unique=False)
    op.create_table('motoboys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motoboys_id'), 'motoboys', ['id'], unique=False)
    op.create_table('rascunhos_pedidos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cliente_telefone', sa.String(), nullable=False),
    sa.Column('conteudo_json', sa.String(), nullable=False),
    sa.Column('ia_sugestao_resposta', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rascunhos_pedidos_id'), 'rascunhos_pedidos', ['id'], unique=False)
    op.create_table('restaurantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('plano', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurantes_id'), 'restaurantes', ['id'], unique=False)
    op.create_table('categorias',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('destino_impressao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('configuracoes_restaurante',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('nicho', sa.String(), nullable=True),
    sa.Column('mapa_mesas_ativo', sa.Boolean(), nullable=True),
    sa.Column('delivery_ativo', sa.Boolean(), nullable=True),
    sa.Column('taxa_servico_ativa', sa.Boolean(), nullable=True),
    sa.Column('taxa_servico_padrao', sa.Float(), nullable=True),
    sa.Column('unificar_vias_delivery', sa.Boolean(), nullable=True),
    sa.Column('modo_exclusivo_salao', sa.Boolean(), nullable=True),
    sa.Column('perm_garcom_delivery', sa.Boolean(), nullable=True),
    sa.Column('perm_garcom_editar', sa.Boolean(), nullable=True),
    sa.Column('perm_garcom_taxas', sa.Boolean(), nullable=True),
    sa.Column('perm_garcom_cancelar', sa.Boolean(), nullable=True),
    sa.Column('perm_garcom_status', sa.Boolean(), nullable=True),
    sa.Column('perm_garcom_abrir_vazia', sa.Boolean(), nullable=True),
    sa.Column('perm_garcom_print', sa.Boolean(), nullable=True),
    sa.Column('perm_garcom_fechar', sa.Boolean(), nullable=True),
    sa.Column('perm_garcom_desconto', sa.Boolean(), nullable=True),
    sa.Column('perm_garcom_acrescimo', sa.Boolean(), nullable=True),
    sa.Column('perm_garcom_pessoas', sa.Boolean(), nullable=True),
    sa.Column('perm_garcom_transferir_mesa', sa.Boolean(), nullable=True),
    sa.Column('perm_garcom_transferir_item', sa.Boolean(), nullable=True),
    sa.Column('perm_garcom_chamar', sa.Boolean(), nullable=True),
    sa.Column('perm_garcom_ociosas', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracoes_restaurante_id'), 'configuracoes_restaurante', ['id'], unique=False)
    op.create_table('distribuidores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('lead_time_dias', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribuidores_id'), 'distribuidores', ['id'], unique=False)
    op.create_table('insumos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('estoque_atual', sa.Float(), nullable=True),
    sa.Column('estoque_minimo', sa.Float(), nullable=True),
    sa.Column('estoque_maximo', sa.Float(), nullable=True),
    sa.Column('unidade_medida', sa.String(), nullable=True),
    sa.Column('preco_medio_custo', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insumos_id'), 'insumos', ['id'], unique=False)
    op.create_table('mesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesas_id'), 'mesas', ['id'], unique=False)
    op.create_table('opcao_modificadores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('grupo_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('preco_adicional', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_modificadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opcao_modificadores_id'), 'opcao_modificadores', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_usuario'), 'usuarios', ['usuario'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('garcom_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['garcom_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('caixa_turnos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aberto_por_id', sa.String(), nullable=False),
    sa.Column('aberto_em', sa.DateTime(), nullable=True),
    sa.Column('fechado_em', sa.DateTime(), nullable=True),
    sa.Column('fechado_por_id', sa.String(), nullable=True),
    sa.Column('saldo_inicial', sa.Float(), nullable=False),
    sa.Column('declarado_dinheiro', sa.Float(), nullable=True),
    sa.Column('declarado_pix', sa.Float(), nullable=True),
    sa.Column('declarado_cartao', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['aberto_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['fechado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caixa_turnos_id'), 'caixa_turnos', ['id'], unique=False)
    op.create_table('comandas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('mesa_origem_id', sa.Integer(), nullable=True),
    sa.Column('garcom_id', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('identificador', sa.String(), nullable=True),
    sa.Column('numero_pedido', sa.Integer(), nullable=False),
    sa.Column('fechada', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('fechado_em', sa.DateTime(), nullable=True),
    sa.Column('valor_pago', sa.Float(), nullable=False),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.Column('delivery_taxa', sa.Float(), nullable=True),
    sa.Column('delivery_telefone', sa.String(), nullable=True),
    sa.Column('delivery_endereco', sa.String(), nullable=True),
    sa.Column('motoboy_id', sa.Integer(), nullable=True),
    sa.Column('status_comanda', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['garcom_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.ForeignKeyConstraint(['motoboy_id'], ['motoboys.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comandas_fechada'), 'comandas', ['fechada'], unique=False)
    op.create_index(op.f('ix_comandas_id'), 'comandas', ['id'], unique=False)
    op.create_index(op.f('ix_comandas_mesa_id'), 'comandas', ['mesa_id'], unique=False)
    op.create_index(op.f('ix_comandas_restaurante_id'), 'comandas', ['restaurante_id'], unique=False)
    op.create_table('notas_entrada',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('chave_acesso', sa.String(), nullable=True),
    sa.Column('numero_nota', sa.String(), nullable=False),
    sa.Column('data_emissao', sa.String(), nullable=True),
    sa.Column('distribuidor_id', sa.String(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['distribuidor_id'], ['distribuidores.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_entrada_id'), 'notas_entrada', ['id'], unique=False)
    op.create_table('observacoes_predefinidas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria_id', sa.String(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observacoes_predefinidas_id'), 'observacoes_predefinidas', ['id'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('categoria_id', sa.String(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('imagem', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    op.create_table('caixa_movimentacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['turno_id'], ['caixa_turnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caixa_movimentacoes_id'), 'caixa_movimentacoes', ['id'], unique=False)
    op.create_table('historico_fidelidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_telefone', sa.String(), nullable=False),
    sa.Column('tipo_movimentacao', sa.String(), nullable=False),
    sa.Column('valor_delta', sa.Float(), nullable=False),
    sa.Column('comanda_id', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comanda_id'], ['comandas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_fidelidade_id'), 'historico_fidelidade', ['id'], unique=False)
    op.create_table('itens_nota_entrada',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('nota_id', sa.String(), nullable=False),
    sa.Column('insumo_id', sa.String(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumos.id'], ),
    sa.ForeignKeyConstraint(['nota_id'], ['notas_entrada.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_nota_entrada_id'), 'itens_nota_entrada', ['id'], unique=False)
    op.create_table('lancamentos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('comanda_id', sa.String(), nullable=False),
    sa.Column('garcom_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comanda_id'], ['comandas.id'], ),
    sa.ForeignKeyConstraint(['garcom_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lancamentos_id'), 'lancamentos', ['id'], unique=False)
    op.create_table('pagamentos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('comanda_id', sa.String(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('metodo', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('cpf_cliente', sa.String(), nullable=True),
    sa.Column('nome_cliente', sa.String(), nullable=True),
    sa.Column('nsu_cartao', sa.String(), nullable=True),
    sa.Column('chave_nfe_emitida', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comanda_id'], ['comandas.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.ForeignKeyConstraint(['turno_id'], ['caixa_turnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamentos_id'), 'pagamentos', ['id'], unique=False)
    op.create_index(op.f('ix_pagamentos_idempotency_key'), 'pagamentos', ['idempotency_key'], unique=True)
    op.create_table('produto_grupo_modificadores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.String(), nullable=False),
    sa.Column('grupo_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_modificadores.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produto_grupo_modificadores_id'), 'produto_grupo_modificadores', ['id'], unique=False)
    op.create_table('itens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('comanda_id', sa.String(), nullable=False),
    sa.Column('lancamento_id', sa.String(), nullable=False),
    sa.Column('produto_id', sa.String(), nullable=False),
    sa.Column('preco_unit', sa.Float(), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('cliente_nome', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('cancelado_por', sa.String(), nullable=True),
    sa.Column('impresso_em', sa.DateTime(), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cancelado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['comanda_id'], ['comandas.id'], ),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_comanda_id'), 'itens', ['comanda_id'], unique=False)
    op.create_index(op.f('ix_itens_id'), 'itens', ['id'], unique=False)
    op.create_index(op.f('ix_itens_restaurante_id'), 'itens', ['restaurante_id'], unique=False)
    op.create_index(op.f('ix_itens_status'), 'itens', ['status'], unique=False)
    op.create_table('item_modificadores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('opcao_modificador_id', sa.String(), nullable=False),
    sa.Column('preco_aplicado', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['itens.id'], ),
    sa.ForeignKeyConstraint(['opcao_modificador_id'], ['opcao_modificadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_modificadores_id'), 'item_modificadores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_modificadores_id'), table_name='item_modificadores')
    op.drop_table('item_modificadores')
    op.drop_index(op.f('ix_itens_status'), table_name='itens')
    op.drop_index(op.f('ix_itens_restaurante_id'), table_name='itens')
    op.drop_index(op.f('ix_itens_id'), table_name='itens')
    op.drop_index(op.f('ix_itens_comanda_id'), table_name='itens')
    op.drop_table('itens')
    op.drop_index(op.f('ix_produto_grupo_modificadores_id'), table_name='produto_grupo_modificadores')
    op.drop_table('produto_grupo_modificadores')
    op.drop_index(op.f('ix_pagamentos_idempotency_key'), table_name='pagamentos')
    op.drop_index(op.f('ix_pagamentos_id'), table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_index(op.f('ix_lancamentos_id'), table_name='lancamentos')
    op.drop_table('lancamentos')
    op.drop_index(op.f('ix_itens_nota_entrada_id'), table_name='itens_nota_entrada')
    op.drop_table('itens_nota_entrada')
    op.drop_index(op.f('ix_historico_fidelidade_id'), table_name='historico_fidelidade')
    op.drop_table('historico_fidelidade')
    op.drop_index(op.f('ix_caixa_movimentacoes_id'), table_name='caixa_movimentacoes')
    op.drop_table('caixa_movimentacoes')
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_observacoes_predefinidas_id'), table_name='observacoes_predefinidas')
    op.drop_table('observacoes_predefinidas')
    op.drop_index(op.f('ix_notas_entrada_id'), table_name='notas_entrada')
    op.drop_table('notas_entrada')
    op.drop_index(op.f('ix_comandas_restaurante_id'), table_name='comandas')
    op.drop_index(op.f('ix_comandas_mesa_id'), table_name='comandas')
    op.drop_index(op.f('ix_comandas_id'), table_name='comandas')
    op.drop_index(op.f('ix_comandas_fechada'), table_name='comandas')
    op.drop_table('comandas')
    op.drop_index(op.f('ix_caixa_turnos_id'), table_name='caixa_turnos')
    op.drop_table('caixa_turnos')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_usuarios_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_opcao_modificadores_id'), table_name='opcao_modificadores')
    op.drop_table('opcao_modificadores')
    op.drop_index(op.f('ix_mesas_id'), table_name='mesas')
    op.drop_table('mesas')
    op.drop_index(op.f('ix_insumos_id'), table_name='insumos')
    op.drop_table('insumos')
    op.drop_index(op.f('ix_distribuidores_id'), table_name='distribuidores')
    op.drop_table('distribuidores')
    op.drop_index(op.f('ix_configuracoes_restaurante_id'), table_name='configuracoes_restaurante')
    op.drop_table('configuracoes_restaurante')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_restaurantes_id'), table_name='restaurantes')
    op.drop_table('restaurantes')
    op.drop_index(op.f('ix_rascunhos_pedidos_id'), table_name='rascunhos_pedidos')
    op.drop_table('rascunhos_pedidos')
    op.drop_index(op.f('ix_motoboys_id'), table_name='motoboys')
    op.drop_table('motoboys')
    op.drop_index(op.f('ix_mensagens_whatsapp_id'), table_name='mensagens_whatsapp')
    op.drop_table('mensagens_whatsapp')
    op.drop_index(op.f('ix_grupo_modificadores_id'), table_name='grupo_modificadores')
    op.drop_table('grupo_modificadores')
    op.drop_index(op.f('ix_configuracoes_ia_id'), table_name='configuracoes_ia')
    op.drop_table('configuracoes_ia')
    op.drop_index(op.f('ix_config_fidelizacao_id'), table_name='config_fidelizacao')
    op.drop_table('config_fidelizacao')
    # ### end Alembic commands ###
