"""Prepare and verify an encrypted off-site package from a validated KÔMA database backup.

This tool never connects to the database. It consumes a folder previously generated by
``scripts/manual_database_backup.py``, verifies the archive SHA-256 against
``manifest.json``, streams the archive + manifest through ``age`` recipient encryption,
and emits a checksum that can be verified after copying the package off the machine.

The age recipient is public. Never pass an age private identity to this script and never
store private identities in the repository.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import hmac
import json
import os
from pathlib import Path
import secrets
import shutil
import subprocess
import tarfile


def sha256_file(path: Path) -> str:
    with path.open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def _write_atomic_text(path: Path, content: str) -> None:
    temporary = path.with_name(f".{path.name}.{secrets.token_hex(4)}.tmp")
    try:
        temporary.write_text(content, encoding="utf-8")
        temporary.chmod(0o600)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def validate_backup_dir(backup_dir: Path) -> tuple[Path, Path, dict]:
    backup_dir = backup_dir.resolve()
    manifest_path = backup_dir / "manifest.json"
    if not manifest_path.is_file():
        raise RuntimeError("manifest.json não encontrado no backup informado.")

    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError("manifest.json inválido ou ilegível.") from exc

    archive_name = manifest.get("archive")
    expected_digest = str(manifest.get("sha256") or "").strip().lower()
    if (
        not isinstance(archive_name, str)
        or not archive_name
        or Path(archive_name).name != archive_name
    ):
        raise RuntimeError("Manifesto não possui nome de archive seguro.")
    if len(expected_digest) != 64 or any(
        char not in "0123456789abcdef" for char in expected_digest
    ):
        raise RuntimeError("Manifesto não possui SHA-256 válido do archive.")

    archive_path = backup_dir / archive_name
    if not archive_path.is_file():
        raise RuntimeError(f"{archive_name} não encontrado no backup informado.")

    actual_digest = sha256_file(archive_path)
    if not hmac.compare_digest(actual_digest, expected_digest):
        raise RuntimeError(
            "SHA-256 do archive não confere com manifest.json; pacote recusado."
        )
    return archive_path, manifest_path, manifest


def package_backup(
    backup_dir: Path,
    output_dir: Path,
    recipient: str,
) -> tuple[Path, Path, Path]:
    recipient = recipient.strip()
    if not recipient:
        raise RuntimeError("Informe o recipient público do age.")

    age = shutil.which("age")
    if not age:
        raise RuntimeError("Utilitário age não encontrado no PATH.")

    archive_path, manifest_path, manifest = validate_backup_dir(backup_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    stem = backup_dir.resolve().name
    encrypted = output_dir / f"{stem}.tar.gz.age"
    checksum = output_dir / f"{encrypted.name}.sha256"
    metadata_path = output_dir / f"{encrypted.name}.metadata.json"
    for path in (encrypted, checksum, metadata_path):
        if path.exists():
            raise RuntimeError(
                f"Destino já existe: {path.name}. Não sobrescreva backups silenciosamente."
            )

    temporary_encrypted = output_dir / (
        f".{encrypted.name}.{secrets.token_hex(4)}.tmp"
    )
    process: subprocess.Popen[bytes] | None = None
    try:
        process = subprocess.Popen(
            [
                age,
                "--encrypt",
                "--recipient",
                recipient,
                "--output",
                str(temporary_encrypted),
            ],
            stdin=subprocess.PIPE,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
        )
        if process.stdin is None:
            raise RuntimeError("Não foi possível abrir o stream de criptografia do age.")

        try:
            # Streaming keeps the plaintext tarball off disk. Only the already existing
            # validated source dump and manifest are read from disk.
            with tarfile.open(fileobj=process.stdin, mode="w|gz") as bundle:
                bundle.add(
                    archive_path,
                    arcname=f"{stem}/{archive_path.name}",
                    recursive=False,
                )
                bundle.add(
                    manifest_path,
                    arcname=f"{stem}/manifest.json",
                    recursive=False,
                )
        finally:
            if not process.stdin.closed:
                process.stdin.close()

        if process.stderr is not None:
            process.stderr.read()
        returncode = process.wait()
        if returncode != 0:
            raise RuntimeError(
                "Falha ao criptografar pacote com age; nenhum pacote foi validado."
            )
        if not temporary_encrypted.is_file() or not temporary_encrypted.stat().st_size:
            raise RuntimeError(
                "O age não produziu um pacote criptografado utilizável."
            )

        temporary_encrypted.chmod(0o600)
        os.replace(temporary_encrypted, encrypted)
    except Exception:
        if process is not None and process.poll() is None:
            process.terminate()
            process.wait()
        temporary_encrypted.unlink(missing_ok=True)
        encrypted.unlink(missing_ok=True)
        raise

    encrypted_digest = sha256_file(encrypted)
    metadata = {
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "source_backup": stem,
        "source_archive": archive_path.name,
        "source_archive_sha256": manifest["sha256"],
        "source_manifest_sha256": sha256_file(manifest_path),
        "source_restore_tested": bool(manifest.get("restore_tested", False)),
        "encrypted_package": encrypted.name,
        "encrypted_package_sha256": encrypted_digest,
        "encryption": "age-recipient",
        "age_recipient": recipient,
    }

    try:
        _write_atomic_text(checksum, f"{encrypted_digest}  {encrypted.name}\n")
        _write_atomic_text(
            metadata_path,
            json.dumps(metadata, indent=2, ensure_ascii=False) + "\n",
        )
    except OSError as exc:
        encrypted.unlink(missing_ok=True)
        checksum.unlink(missing_ok=True)
        metadata_path.unlink(missing_ok=True)
        raise RuntimeError(
            "Não foi possível concluir checksum/metadados; pacote parcial removido."
        ) from exc

    return encrypted, checksum, metadata_path


def verify_package(package: Path, checksum: Path) -> None:
    if not package.is_file() or not checksum.is_file():
        raise RuntimeError("Pacote ou arquivo de checksum não encontrado.")

    line = checksum.read_text(encoding="utf-8").strip()
    expected, separator, filename = line.partition("  ")
    if not separator or filename != package.name:
        raise RuntimeError(
            "Arquivo de checksum não corresponde ao pacote informado."
        )

    expected = expected.strip().lower()
    if len(expected) != 64 or any(
        char not in "0123456789abcdef" for char in expected
    ):
        raise RuntimeError("Checksum SHA-256 inválido.")

    actual = sha256_file(package)
    if not hmac.compare_digest(expected, actual):
        raise RuntimeError("SHA-256 do pacote externo não confere.")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    pack = subparsers.add_parser("pack", help="Criptografar um backup validado.")
    pack.add_argument("--backup-dir", type=Path, required=True)
    pack.add_argument("--output-dir", type=Path, required=True)
    pack.add_argument(
        "--recipient",
        required=True,
        help="Recipient público do age; nunca informe a chave privada.",
    )

    verify = subparsers.add_parser(
        "verify", help="Conferir a cópia externa pelo SHA-256."
    )
    verify.add_argument("--package", type=Path, required=True)
    verify.add_argument("--checksum", type=Path, required=True)

    args = parser.parse_args()
    try:
        if args.command == "pack":
            encrypted, checksum, metadata = package_backup(
                args.backup_dir,
                args.output_dir,
                args.recipient,
            )
            print(f"Pacote criptografado: {encrypted}")
            print(f"Checksum: {checksum}")
            print(f"Metadados: {metadata}")
            print(
                "Copie os três arquivos para fora deste computador e execute "
                "verify contra a cópia externa."
            )
        else:
            verify_package(args.package, args.checksum)
            print("SHA-256 conferido: cópia externa idêntica ao pacote preparado.")
    except RuntimeError as exc:
        print(str(exc))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
